nginx:
  image: nginx
  container_name: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - "/etc/nginx/conf.d"
    - "/etc/nginx/vhost.d"
    - "/usr/share/nginx/html"
    - "/usr/share/nginx/certs:/etc/nginx/certs:ro"
nginx-gen:
  image: jwilder/docker-gen
  container_name: nginx-gen
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
    - "/usr/share/nginx/templates:/etc/docker-gen/templates:ro"
  volumes_from:
    - nginx
  entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
letsencrypt-nginx-proxy-companion:
  image: jrcs/letsencrypt-nginx-proxy-companion
  container_name: letsencrypt-nginx-proxy-companion
  volumes_from:
    - nginx
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - "/usr/share/nginx/certs:/etc/nginx/certs:rw"
  environment:
    - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

clanryan:
  image: nginx
  container_name: cr-web
  volumes:
    - "/usr/share/nginx/clanryan/conf.d:/etc/nginx/conf.d"
    - "/var/www/html:/usr/share/nginx/html"
  environment:
    - VIRTUAL_HOST="www.clanryan.us"
    - LETSENCRYPT_HOST="www.clanryan.us"
    - LETSENCRYPT_EMAIL=joe@clanryan.us
    - LETSENCRYPT_TEST=true
